#!/usr/bin/env bash

## BEGIN_DOC
## This code is a copy of the code found in
## the README file.  It is the most minimal
## example, using a Bash array for the data
## source.
##
## This script performs the 5 basic steps:
## 1. Enable the builtin
## 2. Prepare data source
## 3. Implement line-print function
## 4. Prepare the pwb handle
## 5. Start the interaction
## END_DOC

# Step 1! Enable the builtin
enable pwb

# Step 2: Prepare data source
declare -a FILES=( * )

# Step 3: Implement line-print function
print_line()
{
    local -i index="$1"
    local data_name="$2"
    local -i chars_limit="$3"

    local -n pl_array="$data_name"
    local line="${pl_array[$index]}"

    printf "%-*s" "$chars_limit" "${line:0:$chars_limit}"
}

# Step 4: Prepare the pwb handle
declare PHANDLE
pwb declare PHANDLE FILES "${#FILES[*]}" print_line

# Step 5: Start the interaction
#  'pwb init' prepares the console and 'pwb restore'
#  attempts to put the console back as it found it.
pwb init
pwb start PHANDLE
pwb restore

