.TH 04_ls 7
.SH NAME
.PP
.B 04_ls
Introduction to
.B pwb
margins.
.SH DESCRIPTION
.PP
The first usability enhancement is the use of margins.
.PP
.B pwb
margins can be used as areas to display information, either static
or changing with every new selection, or they can be used simply to
position the main content area.
.PP
The
.B set_margins
action can take one, two, three, or four arguments, corresponding to
the arguments of CSS
.BR margin " and " border
properties.
