#!/usr/bin/env bash

## BEGIN_DOC
## This code is a copy of the code found in
## the README file.  It is the most minimal
## example, using a Bash array for the data
## source.
##
## This script performs the 5 basic steps:
## 1. Establish data source
## 2. Impelement line print function
## 3. Enable pwb builtin
## 4. Prepare pwb handle
## 5. Start the interaction
## END_DOC

# Step 1: establish data source
declare -a FILES=( * )

# Step 2: implement line print function
print_line()
{
    # retrieve data
    local -i index="$1"
    local -n pl_dsource="$2"
    local line="${dsource[$index]}"

    # print data
    local -i chars_limit="$3"
    printf "%-*s" "$chars_limit" "${line:0:$chars_limit}"
}

# Step 3: Enable the builtin
enable pwb

# Step 4: Prepare the pwb handle
pwb declare PHANDLE FILES "${#FILES[*]}" print_line

# Step 5: Start the interaction
pwb init
pwb start PHANDLE
pwb restore

