#!/usr/bin/env bash

## BEGIN_DOC
## This code is a copy of the code found in
## the README file.  It is the most minimal
## example, using a Bash array for the data
## source.
##
## This script performs the 5 basic steps:
## 1. Enable the builtin
## 2. Prepare data source
## 3. Implement line-print function
## 4. Prepare the pwb handle
## 5. Start the interaction
## END_DOC

# Resource #1: Data source
declare -a FILES=( * )

# Resource #2: line print function
print_line()
{
    # retrieve data
    local -i index="$1"
    local -n pl_dsource="$2"
    local line="${dsource[$index]}"

    # print data
    local -i chars_limit="$3"
    printf "%-*s" "$chars_limit" "${line:0:$chars_limit}"
}

# Get PWB running:

enable pwb

declare PHANDLE
pwb declare PHANDLE FILES "${#FILES[*]}" print_line

pwb init
pwb start PHANDLE
pwb restore

