#!/usr/bin/env bash

## BEGIN_DOC
## This script introduces the basics of pwb margins.
##
## Margins are used to establish areas around the main
## content area.  The areas can be left empty as spacing,
## or used as supplemental content areas for instructions
## or context information.
##
## This example simply prints one instruction in the top
## margin area.
## END_DOC

declare -a DIR_FILES=( * )

print_line()
{
    # retrieve data
    local -i index="$1"
    local -n pl_dsource="$2"
    local line="${pl_dsource[$index]}"

    # print data
    local -i chars_limit="$3"
    printf "%s" "${line:0:$chars_limit}"
}

############################
###   EXECUTION BEGINS   ###
############################

enable pwb

pwb declare PHANDLE DIR_FILES "${#DIR_FILES[*]}" print_line

# MARGIN SETTING
# Establish 4-character high margins top and bottom,
# and 20-character margins to left and right.
pwb set_margins PHANDLE 4 20

exit_trap() { pwb restore; }
trap exit_trap EXIT SIGINT SIGABRT

# Save and erase terminal before any cursor addressing
pwb init

# MARGIN PRINTING
# Before starting pwb, print exit instruction in top margin:
declare -a pargs=(
    2                   # row, within the 4-line top margin
    21                  # left margin + 1 to be above content area
    "Press 'q' to exit" # message to print
)

printf $'\e[%d;%dH%s' "${pargs[@]}"

pwb start PHANDLE

