.TH print_functions 7
.SH INTRODUCTION
.PP
.B pwb
fills the terminal screen by delegating the printing to
script-based functions.
.PP
All callback print functions receive the same six arguments:
.TS
tab(|);
l l.
\(Do1|row index (0-based)
\(Do2|data source name
\(Do3|maximum/required width to print
\(Do4|focus, 1 for true: highlighting flag
\(Do5|pwb handle name
\(Do6|extra data name
.TE
.SH LINE PRINT FUNCTIONS
.PP
This is one of the two the basic requirements of a
.B pwb
application, so we have seen the basic implementation of the
line print function in earlier chapters.
.PP
.B pwb
places the cursor into position and calls the line print function,
and the function must only output the line contents.
.SH MARGIN PRINT FUNCTIONS
.PP
Margin-printing functions are more complicated.
While
.B pwb
also positions the cursor at the top left character in the
specific margin and says how wide the text can be, there is
no indication of how many lines nor any help positioning lines
after the first.
.PP
Besides only one call for multiple lines, the other difference
is that the \(Do4/focus argument can be ignore: all margin calls
refer to the newly-selected item.
.PP
One of the main challenges of printing in the margin is that the
normal carriage return will place the cursor at column 1 of the
next line, even if it is out of the boundaries of the margin.
.SH NOTES ON THE SCRIPT
.PP
The script contains several enhancements relative to earlier
chapters.
.TP
.B Custom Highlighting
The script demonstrates custom highlighting.
Having declared the
.B pwb
handle with the
.B -h
flag, the highlighting must be generated by the line print
function.
.IP
Refer to script function
.BR print_line .
.TP
.B Margin Print Function
Shows a solution for the margin print function.
The
.B declare
action must include option
.BI -t " print_top"
to register function
.B print_top
for handling margin printing callbacks.
.IP
See script function
.BR print_top .
.B Column-preserving Text Print Function
One of the difficulties in printing to margins is in preserving
the left column from which the contents should be printed.
The script function
.B center_print
calculates the distance to start a centered line of the
text, prints the line in the appropriate place, then
moves back left to the starting column.
