.TH sources 7
.SH NAME
.PP
.BR sources :
introduction to
.B pwb_sources
and the scriptlets it manages
.SH INTRODUCTION
.PP
The
.B pwb
project includes a library of scriptlets and a script for
managing the inclusion of them in larger script projects.
The purpose of the scriptlets is to package useful code
fragments that can simplify development of Bash applications.
.SS SCRIPTLET DESCRIPTION
.PP
The scriptlets, for the most part, contain a single function
with the same name as the scriptlet that contains it.
.SS PWB_SOURCES TOOL
.PP
There is a tool for including scriptlets, 
.BR pwb_sources ,
that serves four purposes:
.TP
.B pwb_source
Generates a list of available scriptlets
.TP
.B pwb_sources help
Display general usage screen for
.BR pwb_sources .
.TP
.BI "pwb_sources help " scriptlet_name
Display usage screen for script named
.IR scriptlet_name .
.TP
.BI "pwb_sources" " name [name ...]"
Generate Bash code for including missing functions
.SH USING PWB_SOURCES
.PP
The
.B pwb_sources
tool is used in scripts to intellegently include scriptlets in
a project.  Proper use will ensure necessary scripts are included
exactly one time in an application.
.PP
Here is an script usage example:
.IP
.EX
source <( pwb_sources pwb_exit_on_error pwb_conduct_dialog )
.EE
.PP
Many of the scriptlets depend on other scriptlets.  Those with
dependencies contain a global call to
.B pwb_sources
with the list of dependencies, ensuring the function in the
scriptlet has the resources to successfully execute.
.SH SCRIPTLET EXAMPLES
.PP
A
.B pwb
developer should be familiar with the following scriptlets.
They will make development much easier.
.TP
.B pwb_exit_on_error
Is a small error-reporting function that, if used, should immediately
follow a call to
.BR pwb .
If the exit code indicates an error has occurred, it will print a
message listing the line number where the error occurred, and the
error string generated by
.B pwb
to explain the error.
This function is most useful during development to help catch
.B pwb
usage mistakes.
.TP
.B pwb_print_array
This function is designed to help manage margin areas.
.IP
This function prints the contents of an array of text lines
within an area defined by the top/left corner and the number
of lines and the number of columns.
.IP
The lines will be padded with spaces to fill the entire line,
and lines of spaces will be printed to complete the print area
when the array contains too few lines to fill.
.IP
If the number of lines in the array exceeds the number lines in
the print area, the extra lines will be quietly ignored.
.IP
With the padding of lines, and space-filled output for undefined
lines, this function guarantees that the entire print area will
be replaced.
.TP
.B pwb_get_regions
Uses the values from
.BI "pwb get_dimensions " handle_name
to calculate the parameters needed to print in each area (margin
or main content area) of the screen.  The values are returned in an
associative array and are meant to be used with
.B pwb_print_array
to easily fill margin areas.
.TP
.B pwb_printf_limited
Uses the familiar
.B printf
syntax to print a string within a char-count boundary.  The
function counts only printable characters, printing without counting
CSI color strings.  This function enables colorer output to be safely
printed in restricted spaces.
.TP
.B pwb_print_message
Like
.BR pwb_print_array ,
this Will print an array of text lines.  The output of this function
will be centered on the screen and enclosed in a box, making it
useful for communicating with the user.
.IP
A script using this function will be responsible for recognizing
when the message is no longer needed and calling for
.B pwb
to refresh the screen to erase the message.
Hint, use:
.IP
.RS 11
.EX
.BI "pwb print_all " handle_name
.EE
.RE
.IP
to refresh the screen.
